# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.16.14
loom_version=1.10

# Fabric API
fabric_version=0.126.0+1.21.5

# Mod Properties
mod_version=1.13.1
maven_group=me.reimnop
jar_name=discord4fabricMulti

# Dependencies
# check this on https://modmuss50.me/fabric.html
placeholder_version=2.6.4+1.21.5
jda_version=5.6.1
webhook_version=0.8.4
server_translations_version=2.5.0+1.21.5-rc1
player_data_version=0.7.0+1.21.5

# Compat dependencies
vanish_123456687548_version=4717842
vanish_drexhd_version=1.5.17+1.21.5
fabrictailor_version=2.6.6
config2brigadier_version=1.2.5
fabric_permissions_version=0.3.3
